INSERT INTO email_scheduler.recipients (campaign_id, email)
VALUES
(1, 'musicbygini@gmail.com'),
(1, 'kumar@kumarvishwas.com'),
(1, 'sahityatak@aajtak.com'),
(1, 'contact@unmukt.co.in'),
(1, 'thedigitalshayar2020@gmail.com'),
-- (1, 'info@barahe.in'),
(1, 'indianpoetrycollective@gmail.com'),
(1, 'greatindianpoetry@gmail.com'),
(1, 'poetrywala@gmail.com'),
(1, 'indianpoetnikhilparekh@gmail.com'),
(1, '43wcpindia2024@gmail.com'),
(1, 'indianpoetrysociety@gmail.com'),
(1, 'mushairamedia@gmail.com'),
(1, 'zakirkhan208@gmail.com'),
(1, 'baakhararts@gmail.com'),
(1, 'kavisammelanlive@gmail.com'),
(1, 'nexttvc@gmail.com'),
(1, 'nilotpalmrinal.84@gmail.com'),
(1, 'unerasepoetry@gmail.com');







