
INSERT INTO email_scheduler.campaigns (name, subject, body, scheduled_time)
VALUES ('POTERY MAILS', 'KASOORWAR — A Tale of Guilt & Love', 'My name is Jatin, and I’m an independent artist trying to bring my voice to the world.
I recently wrote and recorded a piece that is extremely close to my heart — it’s raw, honest, and comes from real pain and experience.

I am sharing this video with you with a great hope:
if it touches you even a little, please give me just one chance… one stage… one opportunity to be heard.

Your support can change a lot for an artist like me.

Video is attached. Please listen whenever you get a moment — it means a lot to me.

Thank you for your time and kindness.', '09:00');

